### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by AlishahMughal123** [m4ll0k/SecretFinder#15]
![image](https://user-images.githubusercontent.com/52525188/85760019-dfd4dc00-b72a-11ea-8efc-b14f909e855c.png)

**Comment by m4ll0k** [comment]
provide `-e` option: 

`python3 SecretFinder.py -i target.com -e `

**Comment by kssaril** [comment]
Seeing this error with -e option
Traceback (most recent call last):
  File "./SecretFinder.py", line 455, in <module>
    body += '</a><div class="container">%s</div></div>'%(match.get('context')[0])
IndexError: list index out of range

**Comment by AlishahMughal123** [comment]
Oh ohkay thanks let me check 😊

**Comment by m4ll0k** [comment]
https://github.com/m4ll0k/SecretFinder/issues/6#issue-636710123

**Comment by AlishahMughal123** [comment]
It`s working with -e Thanks :)

**Comment by scottishhunter1** [comment]
Exceeded 30 redirects.
when ever i try to run its show this @m4ll0k

**Comment by scottishhunter1** [comment]
le "SecretFinder.py", line 455, in <module>
    body += '</a><div class="container">%s</div></div>'%(match.get('context')[0])
IndexError: list index out of range

**Comment by Anugrahsr** [comment]
Getting the same error when running with -e flag

Traceback (most recent call last):
  File "SecretFinder.py", line 455, in <module>
    body += '</a><div class="container">%s</div></div>'%(match.get('context')[0])
IndexError: list index out of range

**Comment by vaibhavgaikwad1712** [comment]
hey i am getting jsbeautifier error

**Comment by PsOverflow** [comment]
>  am getting jsbeautifier error

Install the required package :
pip install -r requirements.txt
