### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by hackerparakh** [m4ll0k/SecretFinder#24]
Getting following error in secretfinder

/usr/local/lib/python3.8/dist-packages/requests-2.7.0-py3.8.egg/requests/packages/urllib3/connectionpool.py:764: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  warnings.warn((

**Comment by hackerparakh** [comment]
Also
Traceback (most recent call last):
  File "./tools/SecretFinder/SecretFinder.py", line 455, in <module>
    body += '</a><div class="container">%s</div></div>'%(match.get('context')[0])
IndexError: list index out of range

**Comment by hackerparakh** [comment]
Also getting following error
Traceback (most recent call last):
  File "./tools/SecretFinder/SecretFinder.py", line 455, in <module>
    body += '</a><div class="container">%s</div></div>'%(match.get('context')[0])
IndexError: list index out of range

**Comment by m4ll0k** [comment]
#19
