### ISSUE TITLE
No module named 'jsbeautifier'

### ISSUE THREAD

**Issue by lnchandila** [m4ll0k/SecretFinder#25]
when i run the script it show this error

Traceback (most recent call last):
  File "SecretFinder.py", line 16, in <module>
    import jsbeautifier 
ModuleNotFoundError: No module named 'jsbeautifier'

**Comment by m4ll0k** [comment]
python3 -m pip install jsbeautifier  or pip3 install jsbeautifier or pip install jsbeautifier

**Comment by vishal07021998** [comment]
i already installed this but again this give a error
