### ISSUE TITLE
Cannot run SecretFinder because ModuleNotFoundError

### ISSUE THREAD

**Issue by TheCrott** [m4ll0k/SecretFinder#3]
I'm using python 3.6.8 on mac osx 10.14.1

secretfinder$ python SecretFinder.py -i https://code.jquery.com/jquery-3.3.1.js -o cli
Traceback (most recent call last):
  File "SecretFinder.py", line 16, in <module>
    import jsbeautifier
ModuleNotFoundError: No module named 'jsbeautifier'

**Comment by m4ll0k** [comment]
@TheCrott 
`python3 -m pip install jsbeautifier ` or `pip3 install -r jsbeautifier`

**Comment by TheCrott** [comment]
Solved now thanks. I'm missing `pip3` when installing requirements
