### ISSUE TITLE
unterminated character set at position 13

### ISSUE THREAD

**Issue by BreeZeQQ** [m4ll0k/SecretFinder#30]
**python3 SecretFinder.py -i 'example.com_jsfiles/*' -o results.html**

[ + ] URL: file:/example.com_jsfiles\www.example.com\zone.js\dist\assets\js\assets\landing\swiper\assets\js\gsap\gsap.min.js
[ + ] URL: file:/example.com_jsfiles\www.example.com\zone.js\dist\assets\global\js\assets\global\js\browser-detection.js
[ + ] URL: file:/example.com_jsfiles\www.example.com\zone.js\assets\landing\assets\global\js\assets\js\assets\js\gsap\ScrollToPlugin.min.js
[ + ] URL: file:/example.com_jsfiles\www.example.com\zone.js\assets\landing\assets\global\js\environment.js
[ + ] URL: file:/example.com_jsfiles\www.example.com\zone.js\zone.js\dist\assets\landing\swiper\assets\js\assets\global\js\browser-detection.js
[ + ] URL: file:/example.com_jsfiles\www.example.com\zone.js\zone.js\dist\assets\js\assets\landing\gsap\assets\global\js\browser-detection.js
[ + ] URL: file:/example.com_jsfiles\www.example.com\zone.js\assets\landing\assets\js\assets\js\assets\js\jquery-3.5.1.slim.min.js
[ + ] URL: file:/example.com_jsfiles\www.example.com\zone.js\zone.js\dist\assets\js\assets\global\js\assets\js\gsap\ScrollToPlugin.min.js
[ + ] URL: file:/example.com_jsfiles\www.example.com\zone.js\vendor.d9c3b571db2d7a824753.js
[ + ] URL: file:/example.com_jsfiles\www.example.com\zone.js\zone.js\dist\assets\global\js\assets\landing\gsap\TweenMax.min.js
[ + ] URL: file:/example.com_jsfiles\www.example.com\zone.js\main.73bb990592b4d36257fd.js

-----
Traceback (most recent call last):
  File "/home/kali/C2/SecretFinder.py", line 434, in <module>
    matched = parser_file(file,mode)
  File "/home/kali/C2/SecretFinder.py", line 181, in parser_file
    items = getContext(all_matches,content,regex[0])
  File "/home/kali/C2/SecretFinder.py", line 157, in getContext
    context = re.findall('%s%s%s'%(rex,m,rex),content,re.IGNORECASE)
  File "/usr/lib/python3.9/re.py", line 241, in findall
    return _compile(pattern, flags).findall(string)
  File "/usr/lib/python3.9/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.9/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.9/sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.9/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.9/sre_parse.py", line 549, in _parse
    raise source.error("unterminated character set",
re.error: unterminated character set at position 13

**Comment by alonek1** [comment]
I get same errors

**Comment by BreeZeQQ** [comment]
Its about regex problem, you need to delete credentials regex part
