### ISSUE TITLE
The Code is giving me Errors

### ISSUE THREAD

**Issue by MR-pentestGuy** [m4ll0k/SecretFinder#31]
/usr/bin/sensible-browser: 8: open: not found
Start : This command cannot be run due to the error: The system cannot find the file specified.
At line:1 char:1
+ Start "/home/sanath/tools/SecretFinder/output.html"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand

iam using wsl Ubuntu 
i have properly installed sensible-browser 
i am able to open firefox and chrome from sensible-browser

**Comment by 0n1cOn3** [comment]
I find it difficult to close a problem where there is no comment from the developer. 

I whether this problem has been fixed or is still open.🙂
