### ISSUE TITLE
Error while scanning directory with source code

### ISSUE THREAD

**Issue by Karmaz95** [m4ll0k/SecretFinder#44]
Hello, 

The program does not support the directory containing the source code files.

![image](https://user-images.githubusercontent.com/51202595/113143673-b6eaf580-922c-11eb-81e1-f4ea62a60ca5.png)

I have a directory with files:

```bash
directory/
*file1
*file2
*file3
```
I wanted to scan them using `SecretFinder` but with no luck, everytime i see this error:
```
python3 /home/karmaz/tools/SecretFinder/SecretFinder.py -i all_source_code

[ + ] URL: file:///home/karmaz/all_source_code
cat: standard output: Bad file descriptor
```

Could you please add this functionality to your `SecretFinder`

Have a nice day,
Karmaz

**Comment by m4ll0k** [comment]
`python3 /home/karmaz/tools/SecretFinder/SecretFinder.py -i "all_source_code/*" `

**Comment by Karmaz95** [comment]
Still doesn't work

**Comment by m4ll0k** [comment]
`python3 /home/karmaz/tools/SecretFinder/SecretFinder.py -i "all_source_code/*"  -o cli`

**Comment by Karmaz95** [comment]
Nice! It is working, but i will test it more on the next aproach.
Thanks!!
