### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by sawmj** [m4ll0k/SecretFinder#6]
Hello,

Unfortunately when i run the tool while given it a jsfile as input it throw this error,

```
Traceback (most recent call last):
  File "/tools/SecretFinder/SecretFinder.py", line 429, in <module>
    body += '</a><div class="container">%s</div></div>'%(match.get('context')[0])
IndexError: list index out of range

```
Thanks

**Comment by m4ll0k** [comment]
Hi @sawmj 

The problem is when return a empty list in match.get..

edit the code:

```python
# change this line body += '</a><div class="container">%s</div></div>'%(match.get('context')[0]) with:
body += '</a><div class="container">%s</div></div>'%(match.get('context')[0] if match.get('context') != [] else '')

```

**Comment by sawmj** [comment]
Thanks for the fast response
I tried changing that and it gave me this error

```
  File "SecretFinder.py", line 431, in <module>
    match.get('context')[0],
IndexError: list index out of range

```

**Comment by m4ll0k** [comment]
@sawmj  make same thing with next line..

```python 
  body += '</a><div class="container">%s</div></div>'%(match.get('context')[0] if match.get('context') != [] else  '')
                    body = body.replace(
                        match.get('context')[0] if match.get('context') != [] else '',
                        '<span style="background-color:yellow">%s</span>'%(match.get('context')[0] if match.get('context') != [] else '')
                    )
```

**Comment by sawmj** [comment]
it works!
Awesome man keep the good work!

**Comment by HolyBugx** [comment]
Hey , i fixed the source code as you said and the Index Error Problem is Now fixed ,  but i get urllib3 error as following while checking the JS files : 

`InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  warnings.warn((`
