### ISSUE TITLE
error ssl 

### ISSUE THREAD

**Issue by balook** [m4ll0k/SecretFinder#8]
HTTPSConnectionPool(host='www.rockstarnorth.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),)) on trying on some websites gving this error

/SecretFinder.py -o cli -e -i https://www.rockstarnorth.com/

**Comment by m4ll0k** [comment]
@balook  resolved!
