### ISSUE TITLE
Feature: Accept a list of JS files as input

### ISSUE THREAD

**Issue by g33kyshivam** [m4ll0k/SecretFinder#9]
If possible, can we pass a list of JS files collected via recon to check for API keys. Add a switch to pass the filename where there is a list of URLs of JS files.

**Comment by kotlsec** [comment]
ya it will be great like that

**Comment by m4ll0k** [comment]
waiting the next version, you can try this:

```shell

cat my_js_file.txt|xarg -I %% bash -c 'python3 SecretFinder.py -i %% -o cli...'

```
